### ISSUE TITLE
Issue #2: Fix our images 

### ISSUE THREAD

**Issue by Dantusaikamal** [mistrypavankumar/Speech-To-Text#2]
**_Put our images instead of blue circle and move them to centre :)_**

**Comment by Dantusaikamal** [comment]
![Screenshot_2020-07-15-11-59-43-905_com android chrome](https://user-images.githubusercontent.com/65682028/87511478-f79ce180-c692-11ea-9d58-7bb66eb084e9.jpg)

**Comment by mistrypavankumar** [comment]
![team-section](https://user-images.githubusercontent.com/68140538/87512570-e1902080-c694-11ea-80b2-06895f5a6c1f.PNG)

**Comment by mistrypavankumar** [comment]
Issue is fixed
